// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: bid.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BidServiceClient is the client API for BidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidServiceClient interface {
	SubmitBid(ctx context.Context, in *SubmitBidRequest, opts ...grpc.CallOption) (*BidResponse, error)
	ListBids(ctx context.Context, in *ListBidsRequest, opts ...grpc.CallOption) (*ListBidsResponse, error)
	GetAllBidsByTenderId(ctx context.Context, in *GetAllByid, opts ...grpc.CallOption) (*ListBidsResponse, error)
	ListContractorBids(ctx context.Context, in *GetAllByid, opts ...grpc.CallOption) (*GetAllBidsByUserIdRequest, error)
}

type bidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidServiceClient(cc grpc.ClientConnInterface) BidServiceClient {
	return &bidServiceClient{cc}
}

func (c *bidServiceClient) SubmitBid(ctx context.Context, in *SubmitBidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, "/protos.BidService/SubmitBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bidServiceClient) ListBids(ctx context.Context, in *ListBidsRequest, opts ...grpc.CallOption) (*ListBidsResponse, error) {
	out := new(ListBidsResponse)
	err := c.cc.Invoke(ctx, "/protos.BidService/ListBids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bidServiceClient) GetAllBidsByTenderId(ctx context.Context, in *GetAllByid, opts ...grpc.CallOption) (*ListBidsResponse, error) {
	out := new(ListBidsResponse)
	err := c.cc.Invoke(ctx, "/protos.BidService/GetAllBidsByTenderId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bidServiceClient) ListContractorBids(ctx context.Context, in *GetAllByid, opts ...grpc.CallOption) (*GetAllBidsByUserIdRequest, error) {
	out := new(GetAllBidsByUserIdRequest)
	err := c.cc.Invoke(ctx, "/protos.BidService/ListContractorBids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BidServiceServer is the server API for BidService service.
// All implementations must embed UnimplementedBidServiceServer
// for forward compatibility
type BidServiceServer interface {
	SubmitBid(context.Context, *SubmitBidRequest) (*BidResponse, error)
	ListBids(context.Context, *ListBidsRequest) (*ListBidsResponse, error)
	GetAllBidsByTenderId(context.Context, *GetAllByid) (*ListBidsResponse, error)
	ListContractorBids(context.Context, *GetAllByid) (*GetAllBidsByUserIdRequest, error)
	mustEmbedUnimplementedBidServiceServer()
}

// UnimplementedBidServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBidServiceServer struct {
}

func (UnimplementedBidServiceServer) SubmitBid(context.Context, *SubmitBidRequest) (*BidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBid not implemented")
}
func (UnimplementedBidServiceServer) ListBids(context.Context, *ListBidsRequest) (*ListBidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBids not implemented")
}
func (UnimplementedBidServiceServer) GetAllBidsByTenderId(context.Context, *GetAllByid) (*ListBidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBidsByTenderId not implemented")
}
func (UnimplementedBidServiceServer) ListContractorBids(context.Context, *GetAllByid) (*GetAllBidsByUserIdRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContractorBids not implemented")
}
func (UnimplementedBidServiceServer) mustEmbedUnimplementedBidServiceServer() {}

// UnsafeBidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidServiceServer will
// result in compilation errors.
type UnsafeBidServiceServer interface {
	mustEmbedUnimplementedBidServiceServer()
}

func RegisterBidServiceServer(s grpc.ServiceRegistrar, srv BidServiceServer) {
	s.RegisterService(&BidService_ServiceDesc, srv)
}

func _BidService_SubmitBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidServiceServer).SubmitBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BidService/SubmitBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidServiceServer).SubmitBid(ctx, req.(*SubmitBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BidService_ListBids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidServiceServer).ListBids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BidService/ListBids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidServiceServer).ListBids(ctx, req.(*ListBidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BidService_GetAllBidsByTenderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllByid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidServiceServer).GetAllBidsByTenderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BidService/GetAllBidsByTenderId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidServiceServer).GetAllBidsByTenderId(ctx, req.(*GetAllByid))
	}
	return interceptor(ctx, in, info, handler)
}

func _BidService_ListContractorBids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllByid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidServiceServer).ListContractorBids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BidService/ListContractorBids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidServiceServer).ListContractorBids(ctx, req.(*GetAllByid))
	}
	return interceptor(ctx, in, info, handler)
}

// BidService_ServiceDesc is the grpc.ServiceDesc for BidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.BidService",
	HandlerType: (*BidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBid",
			Handler:    _BidService_SubmitBid_Handler,
		},
		{
			MethodName: "ListBids",
			Handler:    _BidService_ListBids_Handler,
		},
		{
			MethodName: "GetAllBidsByTenderId",
			Handler:    _BidService_GetAllBidsByTenderId_Handler,
		},
		{
			MethodName: "ListContractorBids",
			Handler:    _BidService_ListContractorBids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bid.proto",
}
